### PR TITLE
Use httplug instead of old adapter

### PR DESCRIPTION
**Pull request by joelwurtz**
Relink this library to new interface of httplug

Should we rename all "adapter" to client ?

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Thanks, I will try this out with one of the existing adapters, once it is updated.

> Should we rename all "adapter" to client ?

No, I don't think it is necessary. They are still adapters of other, existing clients.

**Comment by joelwurtz** [comment]
It's currenlty running against https://github.com/joelwurtz/socket-adapter-temp (with the last commit)

**Comment by sagikazarmark** [comment]
Ah, cool. Not just cool, awesome.

**Comment by joelwurtz** [comment]
Actually i was having random errors, i have to force the content length header is the tests (to have valid requests) otherwise the php server will throw random errors (for my library)

**Comment by sagikazarmark** [comment]
Hm, what kind of errors?

**Comment by joelwurtz** [comment]
400 Bad request on the PHP server launched by the script

It is mainly due to my adapter which write body by using a buffer (so i do not write the full request on the same call).
So when the php server read the request it may considered it finish but it is not. 

By setting the content-length header we told to the server to wait for X bytes before considering the request finish (which is the correct behavior) the other solution would be to send the request as a chunked one but this is another subject ^^

**Comment by sagikazarmark** [comment]
Great. I don't think it is a hack anyway, so I am fine with having this in the tests by default.

**Pull request merged**
